@CleanArchitectureDemo_HostAddress = http://localhost:5242
###

POST {{CleanArchitectureDemo_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "Laptop",
  "price": 25000,
  "stock": 10
}

### 
GET {{CleanArchitectureDemo_HostAddress}}/api/products
Accept: application/json

###

@productId = 602ff81d-1d27-46fd-8214-c51c2e0c52ea
GET {{CleanArchitectureDemo_HostAddress}}/api/products/{{productId}}
Accept: application/json

